### ISSUE TITLE
Current ami doesn't work on new AWS p3 GPU instances

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/gpu-packer#7]
Using ami `wyss-mlpe-docker-gpu-2017-07-18T20-27-10Z`

![image](https://user-images.githubusercontent.com/233915/32144681-ea33d876-bc92-11e7-9556-4b84a208f94b.png)

Likely related to Issue #6.

Need to update drivers that we're using.

**Comment by grinner** [comment]
This is fixed
